baseURL: 'https://loickpiera.com/'
languageCode: en-us
title: Loïck Piera
theme: ananke

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

enableRobotsTXT: false

paginate: 12

params:
  text_color: ""
  author: ""
  favicon: ""
  site_logo: ""
  description: ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: bg-black
  recent_posts_number: 3
  date_format: ":date_medium"
  custom_css:
    - main.scss

  ananke_socials:
    - name: github
      url: "https://github.com/pyrech"
    - name: twitter
      url: "https://twitter.com/pyrech"
    - name: mastodon
      url: "https://mastodon.social/@pyrech"
      rel: me noopener
    - name: instagram
      url: "https://instagram.com/loick_p"


Social:
  twitter: pyrech

menu:
  main:
    - identifier: contact
      name: Contact
      weight: 1000000
      url: /#contact

deployment:
  matchers:
    # Cache static assets for 1 year.
    - pattern = "^.+\\.(js|css|svg|ttf)$"
      cacheControl = "max-age=31536000, no-transform, public"
      gzip = true

    - pattern = "^.+\\.(png|jpg|jpeg|gif|ico)$"
      cacheControl = "max-age=31536000, no-transform, public"
      gzip = false

    # Set custom content type for /sitemap.xml
    - pattern = "^sitemap\\.xml$"
      contentType = "application/xml"
      gzip = true

    - pattern = "^.+\\.(html|xml|json)$"
      gzip = true
